languageCode = "ko"
languageName = "한글"
weight = 2
title = "jssong84"

[params]
  displayName = "한글"
  isoCode = "ko"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "잘먹고 잘 사는 법."

[params.author]
  name = "송정석"
  email = "nuno@n9o.xyz"
  image = "img/blowfish_logo.png"
  headline = "한글로 써본당."
  bio = "자세한 설명은 생략한다.."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]